import { safeStorage } from 'electron'
import { readdir, readFile, rm, writeFile } from 'fs/promises'
import { join } from 'path'
import { createLogger } from '../utils/logger'
import { paths } from '../utils/paths'
import { ensureDir, pathExists } from '../utils/fs'

/**
 * Encrypted credential storage.
 *
 * Roblox account cookies are bearer tokens: anyone holding one can act as that
 * account. They are therefore never written to Settings.json, Accounts.json or
 * any log. Instead each cookie is encrypted with Electron's `safeStorage`,
 * which on Windows is DPAPI (the same mechanism Chrome uses) and on macOS is
 * the login keychain.
 *
 * When the OS has no usable keyring — typically a bare Linux session — we
 * refuse to persist the cookie rather than falling back to plaintext. Accounts
 * added in that state stay in memory for the session only and the UI is told
 * (`AccountState.secureStorage === false`) so it can say so plainly.
 */

const logger = createLogger('Credentials')

let availabilityCache: { available: boolean; reason: string | null } | null = null

export interface SecureStorageStatus {
  available: boolean
  reason: string | null
}

/** Whether cookies can be persisted on this machine, and why not when they can't. */
export function secureStorageStatus(): SecureStorageStatus {
  if (availabilityCache) return availabilityCache

  let available = false
  let reason: string | null = null

  try {
    available = safeStorage.isEncryptionAvailable()
  } catch (error) {
    reason = error instanceof Error ? error.message : String(error)
  }

  if (!available) {
    reason ??=
      process.platform === 'linux'
        ? 'No OS keyring is available. Install gnome-keyring or kwallet, or start the app with --password-store=basic, to store accounts.'
        : 'The operating system credential store is unavailable, so account cookies cannot be saved.'
    logger.warn(`Secure credential storage unavailable: ${reason}`)
  }

  availabilityCache = { available, reason }
  return availabilityCache
}

/** Test seam: forgets the cached availability result. */
export function resetSecureStorageCache(): void {
  availabilityCache = null
}

function secretFile(id: string): string {
  // Ids are generated by us (hash-based, hex) but sanitise anyway: this value
  // becomes a file name.
  const safe = id.replace(/[^a-zA-Z0-9_-]/g, '')
  if (safe.length === 0) throw new Error('Credential id must contain alphanumeric characters')
  return join(paths.credentials, `${safe}.bin`)
}

/** Encrypts and writes a secret. Throws when encryption is unavailable. */
export async function saveSecret(id: string, value: string): Promise<void> {
  const status = secureStorageStatus()
  if (!status.available) {
    throw new Error(status.reason ?? 'Secure storage is unavailable')
  }

  await ensureDir(paths.credentials)
  const encrypted = safeStorage.encryptString(value)
  await writeFile(secretFile(id), encrypted, { mode: 0o600 })
  logger.info(`Stored credential '${id}' (${encrypted.byteLength} bytes, encrypted at rest)`)
}

/** Reads and decrypts a secret, returning null when it is missing or unreadable. */
export async function loadSecret(id: string): Promise<string | null> {
  const file = secretFile(id)
  if (!(await pathExists(file))) return null

  if (!secureStorageStatus().available) {
    logger.warn(`Cannot read credential '${id}': secure storage is unavailable`)
    return null
  }

  try {
    const buffer = await readFile(file)
    return safeStorage.decryptString(buffer)
  } catch (error) {
    logger.error(`Could not decrypt credential '${id}': ${String(error)}`)
    return null
  }
}

export async function deleteSecret(id: string): Promise<void> {
  try {
    await rm(secretFile(id), { force: true })
  } catch (error) {
    logger.warn(`Could not delete credential '${id}': ${String(error)}`)
  }
}

export async function hasSecret(id: string): Promise<boolean> {
  return pathExists(secretFile(id))
}

/** Ids of every stored credential, used for orphan cleanup. */
export async function listSecrets(): Promise<string[]> {
  try {
    const entries = await readdir(paths.credentials)
    return entries
      .filter((entry) => entry.endsWith('.bin'))
      .map((entry) => entry.replace(/\.bin$/, ''))
  } catch {
    return []
  }
}

/** Removes credential files that no longer belong to a known account. */
export async function pruneSecrets(keep: readonly string[]): Promise<number> {
  const keepSet = new Set(keep.map((id) => id.replace(/[^a-zA-Z0-9_-]/g, '')))
  let removed = 0

  for (const id of await listSecrets()) {
    if (keepSet.has(id)) continue
    await deleteSecret(id)
    removed += 1
  }

  if (removed > 0) logger.info(`Pruned ${removed} orphaned credential file(s)`)
  return removed
}
