/**
 * The names of every glyph `Icon.svelte` can draw. Kept in a plain module so
 * the union can be imported by components and by type-only consumers alike.
 */

export type IconName =
  | 'home'
  | 'palette'
  | 'sliders'
  | 'flag'
  | 'layers'
  | 'plug'
  | 'download'
  | 'info'
  | 'play'
  | 'refresh'
  | 'shuffle'
  | 'external'
  | 'folder'
  | 'trash'
  | 'plus'
  | 'check'
  | 'x'
  | 'minus'
  | 'square'
  | 'copy'
  | 'search'
  | 'chevron-down'
  | 'chevron-right'
  | 'grip'
  | 'alert'
  | 'clock'
  | 'discord'
  | 'github'
  | 'spinner'
  | 'prism'
  | 'code'
  | 'user'
  | 'users'
  | 'globe'
  | 'server'
  | 'broom'
  | 'terminal'
  | 'wrench'
  | 'shield'
  | 'star'
  | 'heart'
  | 'key'
  | 'link'
  | 'gauge'
  | 'save'
  | 'image'
  | 'type'
  | 'music'
  | 'gamepad'
  | 'map-pin'
  | 'cpu'
  | 'zap'
  | 'eye'
  | 'sort'
  | 'edit'
  | 'arrow-left'
